### ISSUE TITLE
Deleting ZIM file should stop playing pip video

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-apple#1003]
If I play a video in pip and delete the source ZIM from the library, then the video continues. It should be stopped.

**Comment by kelson42** [comment]
@BPerlakiH Is that doable?

**Comment by BPerlakiH** [comment]
@kelson42 I am looking into it. It seems we need to close the tabs related to the ZIM content, which eg. in case of macOS is not happening at the moment.

**Comment by kelson42** [comment]
@BPerlakiH This was impacting my iPad

**Comment by BPerlakiH** [comment]
Thank you, I did found a way to handle this on the iPad. I do see related issues on the iPhone and macOS which behave differently, so I will investigate those further.

**Comment by kelson42** [comment]
I obviously don't understand all the details but deleting/unlinking a ZIM file should delete all related items: bookmarks, library entries, tabs... etc.

I would add that should be better be implemented via constraints (for example a tab can not exist if the related library entry does not exist) than imperatively (when I delete a tab, I should check if there is a pip running). Is that doable?

**Comment by BPerlakiH** [comment]
> I obviously don't understand all the details but deleting/unlinking a ZIM file should delete all related items: bookmarks, library entries, tabs... etc.
> 
> I would add that should be better be implemented via constraints (for example a tab can not exist if the related library entry does not exist) than imperatively (when I delete a tab, I should check if there is a pip running). Is that doable?

I will have a look. The things that are reflected in the local DB eg: a Tab, is more closer to those constraints, which you described, whereas some other parts (BrowserViewModel, WKWebView, Picture in Picture) that are more loosely coupled. Some of these are returning pain-points to be honest, so I will think about them, how to do it better for the future.
