### ISSUE TITLE
Access to location pane is hidden

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-apple#1009]
When opening a ZIM file iOS, one has to go to Library > Opened > + > Browse where all local ZIM files are listed.
When the ZIM is not listed there (if it's on a mounted disk for instance or a drive, etc) on has to Click **Browse** icon again, while already being in the **Browse** tab, with it clearly highlighted.

We can not expect users to try to to get there.

See the end of the screencast

https://github.com/user-attachments/assets/f8f4f2cf-3b57-4513-969f-acfd1494131d

**Comment by BPerlakiH** [comment]
Unfortunately this is the default file browser on iOS, which the system provides.
We get the very same for other apps as well (eg. Slack iOS), not just for Kiwix.

There's another way to get to the same state, which is: Browse -> Back button,
equally counter-intuitive if you ask me, but it's not something we can change:

https://github.com/user-attachments/assets/59fbd081-d661-4b41-84e5-3d0d1f0b0d0f

**Comment by rgaudin** [comment]
Do you mean that this whole pane containing Recents, Shared and Browse is provided by the system?

If so, I agree we cant do much about it.

**Comment by kelson42** [comment]
Hould I close the issue as such (without additional thing to do)?
