### ISSUE TITLE
Implement Apple Pay donations for macOS

### ISSUE THREAD

**Issue by BPerlakiH** [kiwix/kiwix-apple#1033]
Re-enable macOS entitlements, that is currently taken out on CI/CD.
See: https://github.com/kiwix/kiwix-apple/pull/1010

Re-enable the UI button for macOS, make sure that the payment session is set up correctly.

**Comment by BPerlakiH** [comment]
I am re-opening this issue, as the CI part still need some fixing.

@rgaudin I have tested locally the following scenarios:
- removed all former certificates
- used the same command line build command as we have on CI:
for macOS:
```
xcodebuild -workspace Kiwix.xcodeproj/project.xcworkspace/ -scheme Kiwix -destination generic/platform=macOS -configuration Release -onlyUsePackageVersionsFromResolvedFile -allowProvisioningUpdates -verbose -archivePath ~/Desktop/Kiwix-CI-mac.xcarchive build
```
for iOS:
```
xcodebuild -sdk iphoneos -workspace Kiwix.xcodeproj/project.xcworkspace/ -scheme Kiwix -destination generic/platform=iOS -configuration Release -onlyUsePackageVersionsFromResolvedFile -allowProvisioningUpdates -verbose -archivePath ~/Desktop/Kiwix-CI-iOS.xcarchive build
```

- I tested that without any certificates both of them are failing (it's expected)
- I created a **macOS Development certificate**, and the macOS build is failing with that:
```
Provisioning profile "Mac Team Provisioning Profile: self.Kiwix" doesn't include signing certificate "Mac Developer ... (9294M4J3B9)". (in target 'Kiwix' from project 'Kiwix')
```
iOS obviously also fails with:
```
No Accounts: Add a new account in Accounts settings. (in target 'Kiwix' from project 'Kiwix')
/Users/balazs/dev/ios/kiwix/Kiwix.xcodeproj: error: No signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team ID "L7HWM3SP3L" with a private key was found. (in target 'Kiwix' from project 'Kiwix')
```
- I created an **iOS Development certificate**, and installed only that, in this case both builds are failing. iOS with:
```
error: No Accounts: Add a new account in Accounts settings. (in target 'Kiwix' from project 'Kiwix')
/Users/balazs/dev/ios/kiwix/Kiwix.xcodeproj: error: Provisioning profile "iOS Team Provisioning Profile: self.Kiwix" doesn't include signing certificate "iPhone Developer: ... (9294M4J3B9)". (in target 'Kiwix' from project 'Kiwix')
```
while macOS with:
```
No Accounts: Add a new account in Accounts settings. (in target 'Kiwix' from project 'Kiwix')
/Users/balazs/dev/ios/kiwix/Kiwix.xcodeproj: error: No signing certificate "Mac Development" found: No "Mac Development" signing certificate matching team ID "L7HWM3SP3L" with a private key was found. (in target 'Kiwix' from project 'Kiwix')
```
- I created an **Apple Development Certificate** (combo for iOS+macOS), and that works for both iOS and macOS builds.


So my suggestion to fix this problem is to remove the iOS and macOS specific certificates, and leave only the "Development All certificate", and make sure we re-export that to .p12 and set that on CI.


![Image](https://github.com/user-attachments/assets/594229d0-4e71-41f1-925c-a0acf28f6079)

**Comment by rgaudin** [comment]
The development All certificate is properly in p12 in the secrets already so you can remove the others if you think that will help. It's easy to re-create if required

**Comment by BPerlakiH** [comment]
Thank you @rgaudin, I have revoked those 2.

**Comment by kelson42** [comment]
@rgaudin I oet you review/merge that one.
