### ISSUE TITLE
Strangely behaving Deeplinks

### ISSUE THREAD

**Issue by kutulus** [kiwix/kiwix-apple#1044]
Kiwix v. 3.6.0 (184) MacOS
Deeplinks in an installed wiki behave strangely.
Example:
zim://DE071ED9-7067-6C01-0EB9-3EC704AB5940/A/Europe

1. if Kiwix is not open, the programme get started and the page of installed wikis is displayed.

2. if Kiwix is open (with the page of the installed wikis), the deeplink is opened in a new window, which is positioned behind the active window

**Comment by BPerlakiH** [comment]
Thank you @kutulus for reporting it. The fix for this will come in our next release.

**Comment by kutulus** [comment]
Hi,
thanks for the prompt reply - and the clarification.

Are there plans to give the user more control over the link target in the future?
Opening a new tab instead of a new window might be a good approach - if the content concerns the same Zim file?

To be honest, the behaviour is very annoying for my use case. I have +1k POI's in a map application from each of which I would like to link to a detail page (e.g. Wikivoyage) in a ZIM archive.
