### ISSUE TITLE
Support iOS 18 Dark Mode App Icons

### ISSUE THREAD

**Issue by tigeryfan** [kiwix/kiwix-apple#1047]
I updated to v3.6.0, and immediately noticed that a iOS 18 dark mode icon is missing. It only supports light mode. Even after a restart, it still persists. Strangely, pre-v3.6.0 versions have an iOS converted icon, and applying a tint "fixes" this issue. I suggest that Kiwix implement a native dark mode icon.

![pre-v6.3.0](https://github.com/user-attachments/assets/f0690148-c72c-46f2-a5e4-e184182c5a3b)![v6.3.0](https://github.com/user-attachments/assets/ce23d2ee-b156-4248-86e3-852adf114e9d)![Tinting](https://github.com/user-attachments/assets/27acdcff-fc15-491c-b95c-b82d15a0225d)

**Comment by rgaudin** [comment]
It's not missing ; it's done like this on purpose as our bird logo is not supposed to be rendered in white. It was broken pre-3.6.

**Comment by tigeryfan** [comment]
Looks like I'm going to have to do some shortcuts custom icons then. The icon really sticks out on my black Home Screen. Thanks for clarifying

**Comment by rgaudin** [comment]
You can find previous icon in the repo: https://github.com/kiwix/kiwix-apple/tree/testflight-3.5.1-release/Support/Assets.xcassets
