### ISSUE TITLE
Export (and share) article feature request

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-apple#180]
add a share button to export page as html (like in safari)

**Comment by kelson42** [comment]
@BeniCydia I don't understand why you need this. What would be exactly the use case?

**Comment by kelson42** [comment]
Without a clear use case, I'm not in favour of this.

**Comment by peterschmidler** [comment]
The use case is to share or print or archive one article, e.g. in order to add it to a paper as a reference.

**Comment by kelson42** [comment]
PDF would be thevproper format IMO.

**Comment by peterschmidler** [comment]
Should be the easiest to develop, on OSX we could also use the Print dialogue. In the long run ODF, HTML, Markdown, Plain Text, ... could be supported.

**Comment by kelson42** [comment]
See also #282

**Comment by kelson42** [comment]
Let me reprhase the ticket. This is about been able on both macOS and iOS to get a PDF (primarly) and either save it to the filesystem or share it with third party apps.

**Comment by BPerlakiH** [comment]
# Suggested system icon for share:
![square and arrow up](https://github.com/kiwix/kiwix-apple/assets/6784320/0b3241f5-36dc-44d5-82c1-101558c10b75)

This can be enabled / disabled depending if we have shareable content loaded on the current screen.

# Suggested placement in the app:

## macOS
<img width="1096" alt="Screenshot 2024-04-14 at 17 25 53 2" src="https://github.com/kiwix/kiwix-apple/assets/6784320/193b0471-89e2-4541-99d0-cc2125997a06">
<img width="1096" alt="Screenshot 2024-04-14 at 17 25 40 2" src="https://github.com/kiwix/kiwix-apple/assets/6784320/255d70ca-7e30-4a64-a2bc-6f247d04817d">



## iPad
![Simulator Screenshot - iPad mini (6th generation) - 2024-04-14 at 17 22 32 2](https://github.com/kiwix/kiwix-apple/assets/6784320/e4865ee0-103a-4e3b-b066-acd1aade16b6)
![Simulator Screenshot - iPad mini (6th generation) - 2024-04-14 at 17 22 27 2](https://github.com/kiwix/kiwix-apple/assets/6784320/dcf4d925-c3f2-4a16-a7f1-fb104762dc15)

## iPhone
![IMG_2805 2](https://github.com/kiwix/kiwix-apple/assets/6784320/a66a218a-10f9-48b7-a101-6510d3447884)
![IMG_2806 2](https://github.com/kiwix/kiwix-apple/assets/6784320/cde631e1-40d7-44e9-844b-b459243e4f0e)

**Comment by kelson42** [comment]
@BPerlakiH I guess the question is about the icon, and this is OK to me
