### ISSUE TITLE
Playing a video should pause any other video already playing

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-apple#198]
Steps to reproduce:
* Start Netflix and play a video
* Thumbnail the video (which continues to play)
* Start Kiwix with a ZIM having a video
* Start the video from Kiwix
* Both video plays together

What I expect:
* Starting the video in Kiwix will pause the Netflix video automatically (this seems to be the standard expected behaviour on iOS)

**Comment by kelson42** [comment]
@BPerlakiH AFAIK this works fine now in latest iOS… but how is the situation wit recent macOS?

**Comment by BPerlakiH** [comment]
@kelson42 I can confirm this works as expected on iOS at the moment.
I did test macOS, the situation is slightly different there: on macOS it is not expected to stop any other video / audio playing. Multiple streams can and should run in parallel. Eg: youtube and soundcloud are happily playing at the same time.
