### ISSUE TITLE
Impossible to seek on videos

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-apple#215]
but it works fine on other ports like android. My guess is that the content is not access directly, instead the whole content is downloaded first.

**Comment by kelson42** [comment]
Basically a duplicate of https://github.com/openzim/youtube/issues/91

**Comment by kelson42** [comment]
Youtube bug has been fixed but it still does not work.

**Comment by kelson42** [comment]
Maybe correlated to #324

**Comment by kelson42** [comment]
@automactic @rgaudin AFAIK It works now with recent ZIM files. You confirm?

**Comment by rgaudin** [comment]
Not for me (1.13.6)

**Comment by rgaudin** [comment]
@kelson42 why are you closing this?

**Comment by kelson42** [comment]
@rgaudin With which ZIM file?

**Comment by rgaudin** [comment]
Tried with Oct. 5 mali ZIM. Do you have a working ZIM for me to test?

**Comment by kelson42** [comment]
@rgaudin sorry, you are right.

**Comment by kelson42** [comment]
I refresh that ticket with an update using iOS 16.4.1 and Kiwix 3.0.2.

Basically it still fail always the same manner: clicking on the progress bar does nothin, the video continues at the current offset.

But it works fine with the three main browsers on iOS using http://library.kiwix.org/viewer#mali-pour-les-nuls_fr_all_2023-03/home.html, so I guess this problem has or might have probably its root cause in Kiwix itself.

**Comment by BPerlakiH** [comment]
@kelson42 please see my findings here: https://github.com/kiwix/kiwix-apple/pull/738

**Comment by kelson42** [comment]
My last status here is that everything works fine on iOS with seeking… but we have problems on macOS!

**Comment by BPerlakiH** [comment]
@kelson42 With the latest develop, and Safari 17 (and higher), which is available from (iOS 17, iPadOS 17) macOS Sonoma, macOS Ventura, and macOS Monterey, there are no problem on macOS.
I've update the wiki page with this info as well, please see here:
https://github.com/kiwix/kiwix-apple/wiki/Known-Issue:-Videos

**Comment by kelson42** [comment]
@BPerlakiH This is ticket for Kiwix

**Comment by BPerlakiH** [comment]
@kelson42 from my research it seems that Safari 17.3 comes pre-installed with macOS Sonoma, therefore the WebKit version there should be able to play webm "natively", and video seeking works perfectly on that.

**Comment by kelson42** [comment]
OK, closing then. In worse case #778 shoukd fix it (for webm). #768 should fix it for mp4.
