### ISSUE TITLE
Print an article on macOS

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-apple#282]
It should be possible to print an article on Kiwix for macOS.
Shortcut CTRL+P should be implemented.

**Comment by hqrshguptq** [comment]
Hi, I need to participate in GSoD this year at WIkiMedia and have some prior experience of both Technical Writing and iOS development.
Could you let me know which is the best place to start with and if you can introduce to me some good first issues for contributions..

**Comment by thesenatorO5-2** [comment]
It is Cmd+P.

**Comment by TheMathGuyd** [comment]
To add to the importance of this issue, I only downloaded Kiwix because the wiki (falsely) claims since 2013 in the UserGuide that the program can export/print.
https://wiki.kiwix.org/wiki/User_guide

> You can print the Kiwix pages or even export and share them. There are three options available:
> 
> To print a page you are viewing in Kiwix, click on the Print icon in the toolbar or press Ctrl+P (⌘-P on Mac). This option is also available in File menu. You will be able to preview the page and adjust basic printer and page settings, before printing. Make sure the computer connected to the printer is also turned on.
> To export a page to PDF format, go to File > Print as PDF menu item or just press Ctrl+Shift+D (⌘-Shift-D on Mac). It will convert the page into a PDF file which can be used to print or read the document later. Note that the output has been prepared for printing and the internal links will be removed from the page.
> To save the page as an HTML or text file, go to File >  Save page as menu item or just press Ctrl+S (⌘-S on Mac). Although it is not appropriate for sharing, the HTML format will keep the same formatting and links of the page.

**Comment by rgaudin** [comment]
@TheMathGuyd sorry about that

- That user guide is for a previous version of Kiwix
- That version has been replaced with kiwix-desktop ; which also supports printing
- That version is Linux/Windows
- The macOS app is a different codebase and doesn't allow print at the moment (hence this ticket)

@kelson42 @Popolechien we should clean up oudated information from the Wiki

**Comment by Popolechien** [comment]
@kelson42 this page refers to Kiwix 0.9 - time to deprecate / delete?

**Comment by kelson42** [comment]
Honestly i would expect to see the feature implemented soon as this is an important one... and easy to implement (my best guess).

**Comment by BPerlakiH** [comment]
@kelson42 The iOS part is already merged here, please see the screenshot:
https://github.com/kiwix/kiwix-apple/pull/729
