### ISSUE TITLE
Replace file License headers to match GLPv3

### ISSUE THREAD

**Issue by BPerlakiH** [kiwix/kiwix-apple#575]
In an attempt to unify the header of each source file, including new ones, we want to apply a common template, and replace the existing ones across the code base.

**Comment by BPerlakiH** [comment]
Can we define here how the header should look like, to be GLPv3 compliant?
Then I can replace them across the project, and set it in a template, so new files are created with that from then on.

**Comment by kelson42** [comment]
Yes I will, but not a prio for the moment.
