### ISSUE TITLE
[feature request] share button for content in page

### ISSUE THREAD

**Issue by SuperCowProducts** [kiwix/kiwix-apple#608]
## Specs

OS: iPadOS 17.1.2
Kiwix 
-version: 3.2
-build: 123

## Intro

When browsing a wikipedia page, there's no way to search text / copy all content to browse / annotate / etc. in a different app. 

## Suggestion

A way of 'sharing' the page (a share button that opens up a kind of share sheet) would be great for quickly accessing the same content on a different app, with added functionality very useful for researching and studying. 

## Conclusion

That way it wouldn't be necessary to implement all these features directly on the kiwix app: an app of the user's choosing could take care of all that, and kiwix would remain the offline source of internet information such as Wikipedia articles.

**Comment by kelson42** [comment]
Works for me, see screenshot
<img width="1024" alt="image" src="https://github.com/kiwix/apple/assets/1029718/6a55e2f6-7e3b-48a1-bf76-b808113b8f20">

**Comment by kelson42** [comment]
Closing the ticket. @SuperCowProducts Please reopen/comment if I have misunderstood something,

**Comment by SuperCowProducts** [comment]
Sorry for the confusion, looks like I didn't highlight why I wanted a button to share the _whole content_ on the page, not just a selected part.

## The issue

Unless one's using a hardware keyboard and thus able to take advantage of the CNTRL-A shortcut, moving _everything_  into a different app (this is not only but _also_ useful as a  temporary workaround for the "find" function that is being worked on) is very time-consuming and potentially impractical if the page is particularly long to scroll down under and therefore manually select: this is currently the only way to select all text because the menu that pops up when pressing down text for a long duration doesn't include a "Select All" option. 

In a way, a share button that captures the whole page could substitute the all-important  "Select All" option missing from the pop-up menu.

**Comment by kelson42** [comment]
@SuperCowProducts what is the exact use case pr problematic you have in mind? Would a send artivle as pdf some kind of thing you had in mind?

**Comment by SuperCowProducts** [comment]
I would use this feature mainly for annotating, either in a PDF editor such as 'Xodo', or in a note-taking app like 'Obsidian'. 

In that case having the whole page to work with in one place is more useful than having to copy and paste bits of it as I search for and underline/highlight the information I need.

**Comment by kelson42** [comment]
@SuperCowProducts If the goal is to annotate the content, why not adding this feature directly in Kiwix?

**Comment by kelson42** [comment]
I‘m really not convinced we should build in a system to make notes, but we are committed to allow easy full article PDF export, see #180
