### ISSUE TITLE
Systematic crash at start after update to 3.3

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-apple#675]
After updating from 3.1 (App store version) to Testflight 3.3 on my macOS 12.6.6, the app just crash at launch every time.

**Comment by kelson42** [comment]
@BPerlakiH How would look ike the procedure to share all my local Kiwix config so you can test and reproduce the bug?

**Comment by BPerlakiH** [comment]
I am not sure, it might be down to the macOS version, but might as well be related to the other crash issue.
Unfortunately TestFlight is not really helpful, and not providing at the moment any details of crashes, or even installs at the moment (according to the "help buble" on developer.appple.com it can take up to 72 hours things to appear.
At this stage, I would recommend to retest this once we have [this PR merged](https://github.com/kiwix/apple/pull/677/files).

**Comment by BPerlakiH** [comment]
I've just started the Testflight process for the latest main branch (as the above PR was merged). 
Once available, it should be re-tested on a clean environment, which can be achieved the following way:
- Open Applications -> Move Kiwix to Trash
- Empty Trash
- from the command line run: `rm -rf ~/Library/Containers/self.Kiwix`

**Comment by kelson42** [comment]
@BPerlakiH Stll crashing with testflight version of last night

**Comment by BPerlakiH** [comment]
I managed to re-create this one, it seems to be related to the largest file:
"canadianprepper_en_all_2023-11.zim"
it was downloading on my side for quite some time, so I am not sure if it's not corrupted in some way,
nevertheless, it causes the same kind of crash.
The exception thrown by libzim in `ZimFileService`:
```
+ (ZimFileMetaData *)getMetaDataWithFileURL:(NSURL *)url {
    ZimFileMetaData *metaData = nil;
    [url startAccessingSecurityScopedResource];
    try {
        kiwix::Book book = kiwix::Book();
        zim::Archive archive = zim::Archive([url fileSystemRepresentation]); // <---- crash is here
        book.update(archive);
        metaData = [[ZimFileMetaData alloc] initWithBook: &book];
    } catch (std::exception e) { }
    [url stopAccessingSecurityScopedResource];
    return metaData;
}

// Thread 1: Swift runtime failure: unhandled C++ / Objective-C exception
```
cannot be caught, and crashes the application.

**Comment by kelson42** [comment]
Root cause of this behaviour is https://github.com/openzim/libzim/issues/866. Keeping this ticket open for tracking.

**Comment by kelson42** [comment]
@BPerlakiH Can you please check if it works now and close if fixed?

**Comment by BPerlakiH** [comment]
@kelson42 I am happy to close this, it seems to be working as expected.
