### ISSUE TITLE
Rename repository from `apple` to `kiwix-apple`

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-apple#709]
This is a matter of clarity and coherency (with other repositories).

**Comment by kelson42** [comment]
@rgaudin @BPerlakiH @automactic OK for you? Do you believe there is something special we should take care of?

**Comment by rgaudin** [comment]
OK ; we'll have to fix custom apps workflows though

**Comment by kelson42** [comment]
OK, will do that today
