### ISSUE TITLE
iOS opening the main page from the ZimFile Details don't close the presented sheet

### ISSUE THREAD

**Issue by BPerlakiH** [kiwix/kiwix-apple#714]
The button does open the main page of the ZIM file selected from the details, but it does so "in the background" on iOS.
This is not intuitive at all.

Solution: if we open the main page, close the presented pop-up on iOS.

![Simulator Screenshot - iPhone 15 - 2024-03-25 at 01 54 07](https://github.com/kiwix/apple/assets/6784320/c3e8176f-4d71-4b27-bb38-d94338ab4d2b)

**Comment by kelson42** [comment]
I don't understand this issue. I don't see any popup. Mainpage is properly open.

**Comment by BPerlakiH** [comment]
There are still some edge cases to be fixed, therefore re-opening it.
