### ISSUE TITLE
German Wikipedia

### ISSUE THREAD

**Issue by flyingfarmer** [kiwix/kiwix-apple#732]
Since a while it is no more possible to load the german Wikipedia file. Any idea why?

**Comment by kelson42** [comment]
@flyingfarmer Please describe step-by-step what you do, what you get and what you expect.

**Comment by flyingfarmer** [comment]
On my iPhone iOS 17 I open the Kiwix App, then I press fetch catalog. In section Wikipedia I only see the english version for download.

**Comment by Popolechien** [comment]
I see the last couple of runs worked fine and the last version is indeed available on the Library: https://library.kiwix.org/viewer#wikipedia_de_all_maxi_2024-04

May be an issue with iOS or your own settings (I'm no iOS user, not sure how language settings work)

**Comment by flyingfarmer** [comment]
There is no option to set the language in the kiwix app. I already deleted and downloaded the latest version again.

**Comment by Popolechien** [comment]
> There is no option to set the language in the kiwix app
Odd. Are you general phone settings set to English? In that case Kiwix would pick up on them and filter content for download to English as well.

**Comment by flyingfarmer** [comment]
No, the iPhone language is german (I double checked). When I click on open file the Kiwix app is german, click on fetch catalog brings up english language.

**Comment by kelson42** [comment]
@flyingfarmer I strongly suspect we have here a UI related problem. We will release within two weeks version 3.3.0 which has fully revamped the UI language mgmt and pretty sure this will fix this issue. Thx for your patience.

**Comment by flyingfarmer** [comment]
Okidoki, looking fwd tobit. Thx for support!

**Comment by flyingfarmer** [comment]
Hi there, what about the update?

**Comment by flyingfarmer** [comment]
New version is online, problem solved. Thx
