### ISSUE TITLE
Button export wrongly displayed

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-apple#749]
<img width="1024" alt="image" src="https://github.com/kiwix/kiwix-apple/assets/1029718/4ef6ee71-2812-4b17-b957-6822b1ea565f">

**Comment by kelson42** [comment]
@BPerlakiH I guess this is because there is no translation in French, but then it should be in English

**Comment by BPerlakiH** [comment]
@kelson42 I must have missed the key component for localisation for this entry.
With the following it should be good:
https://github.com/kiwix/kiwix-apple/pull/750/files
