### ISSUE TITLE
Temporarily remove the "Support Kiwix" link from the apps

### ISSUE THREAD

**Issue by BPerlakiH** [kiwix/kiwix-apple#752]
Apple's suggested solution for non-profits can be found here:
https://developer.apple.com/apple-pay/nonprofits/

According to App Store rules, it is not allowed to use external links (this way) that leads to any kind of purchase (even donations).
For this reason in release 3.3.0 the links to "Support Kiwix"should be removed.

**Comment by kelson42** [comment]
OK, a ticket ahould be created for the alternative solution

**Comment by BPerlakiH** [comment]
@kelson42 ticket created: https://github.com/kiwix/kiwix-apple/issues/753

**Comment by rgaudin** [comment]
Note written but I believe this is due to our publishing it into the Mac App Store.
Do we want to keep it for the DMG version? How easy is it to toggle this based on a build flag?

**Comment by BPerlakiH** [comment]
I think it is possible to toggle this based on a build flag. The more important question is if we really want to.
Once Apple Pay will be in implemented, that is a better user experience, than the external link IMHO (users are more likely to pay if it's easier, leading to more donations, I suppose).

**Comment by rgaudin** [comment]
I don't know enough about this but:

- Would this Apple Pay donation mechanism work with a DMG distributed outside the App Store?
- Would it allow direct donations without requiring an Apple account?

**Comment by BPerlakiH** [comment]
- I am not sure if it works on DMG, never tried that to be honest. There's also Apple Pay for web, so theoretically it should work. We can also test it before release, there's even a sandbox testing environment.
- [Apple Pay can only be used with an Apple ID a compatible device and a card (participating)](https://support.apple.com/en-us/HT204506#:~:text=To%20use%20Apple%20Pay%2C%20you,in%20to%20your%20Apple%20device.). It has some limits on the supported countries / participating banks as well: https://support.apple.com/en-in/102775.
- Alternatively we can include both the link and Apple Pay in the DMG version...

**Comment by kelson42** [comment]
@rgaudin's proposal makes sense, this is what we do for Kiwix Android.
