### ISSUE TITLE
Should we use phased release?

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-apple#759]
App Store allows us to release in phases: instead of all users being notified of the update when we click the release button, percentages of our users base gets it over a 7 days period.

At any time, anyone can still access the app's page on the store and download (it's released).

See [documentation](https://developer.apple.com/help/app-store-connect/update-your-app/release-a-version-update-in-phases)

The advantage of this tool seem to be to pause or cancel a release before it hits everyone, in the event that there's a problem with the release.

In such event, a number of people would already be affected by a _broken_ version, we'd still have to quickly release a fix.

I have no strong opinion. Given the low feedback we receive, I don't think it's gonna be much beneficial while keeping updates from users for 7d can feel unfair.

**Comment by kelson42** [comment]
@rgaudin @BPerlakiH We must do so for given reason: full straight release is uselessly dangerous. Please taking all the necessary measures to release that way.

**Comment by kelson42** [comment]
This having been said, do we need to keeo this ticket open?

**Comment by rgaudin** [comment]
Until option is enabled in AppStoreConnect…

**Comment by kelson42** [comment]
@BPerlakiH Can you please do the necessary so we can close this issue?

**Comment by BPerlakiH** [comment]
@kelson42 I've created the next release versions under the developer account (3.4.0) and set both iOS and macOS to phased release, with that I think we can close this ticket.
