### ISSUE TITLE
Should we rename DMG files and corresponding folder?

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-apple#760]
Our standalone macOS release, available at https://download.kiwix.org/release/kiwix-desktop-macos/ is named:

```
kiwix-desktop-macos_3.3.0.dmg
```

According to [Branding](https://github.com/kiwix/overview/wiki/Branding), this reader's name is `Kiwix` (that's the name of the App inside the DMG) and **could be** `Kiwix macOS` if listed alongside others.

Given this release folder only serves various versions of the same reader, it would seem logical to list files as `Kiwix-3.3.0.dmg` for instance.

**Comment by Popolechien** [comment]
Seems about right.

**Comment by kelson42** [comment]
The name should be "kiwix-macos_3.3.0.dmg" according to the branding and that would be OK to me.

I don't like "kiwix_3.3.0.dmg", not only because this does not respect the branding, but alos because ultimatevely we could have "kiwix_2.4.0.exe" and because of the versioning discrepancy this might lead to confusion.

**Comment by rgaudin** [comment]
Fixed in https://github.com/kiwix/k8s/commit/f1d5e594b4145bc4af34e1a6a54262ddfab72844 ; old links are still working.

**Comment by rgaudin** [comment]
Pushed directly as workflow was reviewed yesterday ; just adjusted to new name

**Comment by kelson42** [comment]
@rgaudin Can we also update please the folder name coherently?

**Comment by rgaudin** [comment]
What would be the folder name? Is `kiwix-macos` OK ?

This is the current list

```
browsers
firefox-os
kiwix-android
kiwix-desktop
kiwix-desktop-macos
kiwix-hotspot
kiwix-js-electron
kiwix-js-windows
kiwix-tools
libkiwix
ubuntu-touch
```

**Comment by kelson42** [comment]
@rgaudin Yes "kiwix-macos"

**Comment by rgaudin** [comment]
Done.
