### ISSUE TITLE
Video playback status

### ISSUE THREAD

**Issue by BPerlakiH** [kiwix/kiwix-apple#765]
After throughout investigation of our current status of video playback on macOS and iOS, using the TED test content, here's the summary of what is working and what is not.

### macOS: safari browser using caddy server
player | HTML5 | OGVJS
-- | -- | --
plays audio / video | 1 | 1
user can seek | 1 | 1
uses range requests | 0 | 1
fullscreen | 1 | 1

###  iOS: safari browser using caddy server
player | HTML5 | OGVJS
-- | -- | --
plays audio / video | 1 | 0
user can seek | 1 | 1
uses range requests | 0 | 1
fullscreen | 1 | 0

### macOS: in app webkit browser using content from caddy
player | HTML5 | OGVJS
-- | -- | --
plays audio / video | 1 | 1
user can seek | 1 | 1
uses range requests | 0 | 1
fullscreen | 1 | 0

### iOS: in app webkit browser using content from caddy
player | HTML5 | OGVJS
-- | -- | --
plays audio / video | 1 | 0
user can seek | 1 | 1
uses range requests | 0 | 1
fullscreen | 1 | 0

### macOS: in app webkit browser using content from ZIM file
player | HTML5 | OGVJS
-- | -- | --
plays audio / video | 1 | 1
user can seek | 1 | 0
uses range requests | 0 | 1
fullscreen | 1 | 1

### iOS: in app webkit browser using content from ZIM file
player | HTML5 | OGVJS
-- | -- | --
plays audio / video | 1 | 0
user can seek | 1 | 0
uses range requests | 0 | 1
fullscreen | 1 | 0

**Comment by BPerlakiH** [comment]
@kelson42 I did manage to test the scenario you mentioned earlier:
- have the video pre-loaded (on a slower network - in my case wifi was enough for this)
- before the content is fully loaded, press play, and quickly seek to the end of the video
**Result**: The video continues playing the content that was already loaded, but in a "fast forward" way, with playback speed of ~2x.

**Comment by kelson42** [comment]
@BPerlakiH Sorry but this is not what I request yesterday: I have specifically request a wiki page for end-users. Here is the issue https://github.com/kiwix/kiwix-apple/issues/766
