### ISSUE TITLE
Document known issues with video handling in the wiki

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-apple#766]
Document for end-users in the wiki at the page „Video Playback“ what works and what does not work regarding video playing.

This page should provide the following tables with for each entry either the „check“ or „fail“ unicode character:
* „Latest Web Browsers: in X „Quick start, Playing, Seeking, Fullscreen“ and in Y „Ff iOS xyz, Chrome iOS xyz, Safari iOS xyz, FF macOS xyz, chrome macos XYZ, safari macos xyz. Exact version of browser and OS should be documented. This should be done for the two last main releases of iOS and macOS AFAP. Should be done with latest Working ZIM file in kiwix-serve.
* „Kiwix“: same X values and Y values (2 latest main releases of macOS and iOS)

Add a section in READMe explaining that we know we have a few issues around video playing and pointing to the wiki page

**Comment by BPerlakiH** [comment]
@kelson42 please see the wiki updated here: https://github.com/kiwix/kiwix-apple/wiki/Known-Issue:-Videos
