### ISSUE TITLE
Support range requests for video content

### ISSUE THREAD

**Issue by BPerlakiH** [kiwix/kiwix-apple#767]
Make sure our application is capable of handling range requests for video content.

Background: as of our current investigation the currently working html5 video player (for latest 17.3+ iOS) do not create range requests. These requests might appear at some point, we want to make sure we are prepared for it.

**Comment by kelson42** [comment]
Still the priority, but would like to release 3.4.0 before.

**Comment by kelson42** [comment]
@BPerlakiH @rgaudin Please organise a meeting together to assess current situation and sketch a plan to move forward

**Comment by rgaudin** [comment]
I don't think there's been effort on this direction recently.
To me there is still a technical assessment that must be conducted: how does it work with major browsers over HTTP? How does it work with the WKWebView over HTTP? How does it _work_ in app mode (Custom Scheme and WKWebView)?
This is a mandatory first step IMO to understand what should be changed and why.
I believe browser behavior adapt to environment/network so results might be complex and require peeking at source code.

This implies having a proper testing setup with identical videos of various sizes.
