### ISSUE TITLE
After resuming app (iOS) video displayed black

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-apple#772]
- Watching a video
- Pausing
- Starting another app
- Coming back to Kiwix and getting

<img width="1080" alt="image" src="https://github.com/kiwix/kiwix-apple/assets/1029718/a655f8cd-fa4f-4088-bd9b-f56f5192f08e">

Video should display proper frame.

**Comment by BPerlakiH** [comment]
I assume it's on an iPad right?

I could not recreate this issue on iPad OS 17.4.1, with the current main branch (as of 30 May).
I did tried to background the app, open another one, I even tried split view mode, but the video is playing as expected.

**Comment by kelson42** [comment]
> I assume it's on an iPad right?

Yes, iPadOS 17.5.1

**Comment by BPerlakiH** [comment]
Ok, I was able to reproduce it, by opening another high consumption app.

**Comment by kelson42** [comment]
@BPerlakiH This issue is the next one to fox and then #768 should be completed

**Comment by kelson42** [comment]
Still buggy, not even after hinübernating, just after going shortly in background:
<img width="1080" alt="image" src="https://github.com/kiwix/kiwix-apple/assets/1029718/0fc7f505-ae34-4bcd-89fd-03388131fcea">

then going breifly to background
<img width="1080" alt="image" src="https://github.com/kiwix/kiwix-apple/assets/1029718/16b8eee3-f62d-4318-a66c-f09dfa02f8bf">

**Comment by BPerlakiH** [comment]
@kelson42 I could not re-create this issue on my iPad (with the current main branch), what was the video that you were using ?

**Comment by kelson42** [comment]
> @kelson42 I could not re-create this issue on my iPad (with the current main branch), what was the video that you were using ?

https://mega.nz/file/XRE2VBrI#U0sPZQ6dttL4alTnuQz6rc3e7G2lEr588hMENer-XUE
