### ISSUE TITLE
`mailto:` links are not opening the OS-configured mail application

### ISSUE THREAD

**Issue by benoit74** [kiwix/kiwix-apple#780]
ZIM: https://mirror.download.kiwix.org/zim/.hidden/dev/fas-military-medicine_en_2024-05.zim
Kiwix app: 3.4.0 (161) - Testflight
OS: MacOS Sonoma 14.5

When clicking on `Steve Aftergood` at the bottom of the front page, we should open a `mailto:` link. This does not happen (while it does work on Firefox on same machine, so handling of mailto links seems to be properly configured at OS level (is it an OS-wide configuration?).

**Comment by kelson42** [comment]
Tested with latested tesflight, and once i have accepted to open external link, the whole app crash
