### ISSUE TITLE
On macOS the video is not "taking up" the full screen

### ISSUE THREAD

**Issue by BPerlakiH** [kiwix/kiwix-apple#785]
This might happen depending on the initial size of the app screen.

The current user work around is: hide the side bar, and make the app itself full screen first using the green system icon (top left corner). After this make the video content full screen.

We should fix this issue, so that the user won't have to do any workarounds, and the video should work in full screen, regardless of the current window size, or side bar visibility.

**Comment by kelson42** [comment]
@BPerlakiH This issue is the priority to fix

**Comment by BPerlakiH** [comment]
@kelson42 please see the fix here: https://github.com/kiwix/kiwix-apple/pull/791
