### ISSUE TITLE
ZIM metadata „illustration“ is not read properly

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-apple#789]
Here we have a proper logo (with Kiwix Server)
https://dev.library.kiwix.org/#lang=&q=Mali+mp4

But the same file in the Kiwix local library displays the defaukt logo placeholder
<img width="1080" alt="image" src="https://github.com/kiwix/kiwix-apple/assets/1029718/6f0c83e5-76b7-45b7-be0c-e5934d21abbb">

**Comment by kelson42** [comment]
Not sure how this is done, but there is a primitive in libkiwix which shiukd be used:
https://libkiwix.readthedocs.io/en/latest/api/classkiwix_1_1Book_1_1Illustration.html?highlight=Illustration

I suspect that because the logo of the ZIM is accessed directly and because we have changed in the path the URL, then something is wrong. Please read https://wiki.openzim.org/wiki/Metadata

**Comment by rgaudin** [comment]
The reader is using its [`url`](https://libkiwix.readthedocs.io/en/latest/api/classkiwix_1_1Book_1_1Illustration.html#class-documentation) property

```cpp
book->getIllustrations().at(0)->url
```

Documentation is of no help here but a quick glimpse at the code have me believe that `url` is only set when read from XML or from OPDS so in apple reader's case, only if downloaded from the catalog. I could confirm this with a test.

@BPerlakiH, we should use `getData()` indeed.
A quick hack could be returning a base64 image/png url as this is used as an URL 😝

**Comment by kelson42** [comment]
Makes sense, metadata should be retrieved from online catalogue AFAP, but if no entry there, ALL metadata (illustration included) should come from the ZIM file.

**Comment by kelson42** [comment]
Still not working:
<img width="1080" alt="image" src="https://github.com/kiwix/kiwix-apple/assets/1029718/acc3880f-0cc0-4a50-8d77-e33119e43509">

**Comment by kelson42** [comment]
After iOS update to version 18... it works!
<img width="1080" alt="image" src="https://github.com/kiwix/kiwix-apple/assets/1029718/5350c2c6-f416-4539-bc53-83fe80b619ca">

I'm a bit puzzled.

**Comment by rgaudin** [comment]
Given you use this device to test the app, I'm not sure it's a wise choice to be on a beta system… but there's no downgrade possible so it's too late now 😀

**Comment by kelson42** [comment]
> Given you use this device to test the app, I'm not sure it's a wise choice to be on a beta system… but there's no downgrade possible so it's too late now 😀

Yes, but see it the other way: we prefer to detect problems wirt iOS earlier, better than waiting the system is live.

**Comment by rgaudin** [comment]
I figured, but you're the only tester we have! Hope it works well on current stable!

**Comment by rgaudin** [comment]
Current Testflight for macOS (published 3days ago) still exhibits the bug

<img width="1279" alt="Screenshot 2024-06-27 at 16 22 23" src="https://github.com/kiwix/kiwix-apple/assets/57929/3942ff62-842e-46fc-835f-4c259715b9b0">

**Comment by kelson42** [comment]
@rgaudin Thx, I wonder if there is not a cache somewhere which would make the test of the patch complicated!?

**Comment by BPerlakiH** [comment]
> Current Testflight for macOS (published 3days ago) still exhibits the bug
> 
> <img alt="Screenshot 2024-06-27 at 16 22 23" width="1279" src="https://private-user-images.githubusercontent.com/57929/343861689-3942ff62-842e-46fc-835f-4c259715b9b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1ODEwOTAsIm5iZiI6MTcxOTU4MDc5MCwicGF0aCI6Ii81NzkyOS8zNDM4NjE2ODktMzk0MmZmNjItODQyZS00NmZjLTgzNWYtNGMyNTk3MTViOWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDEzMTk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2YzYzYTExM2JkZDY4YzEyYTYzMDcyZWIxODJiNDNkN2Y3YjVhZDU2Mjc3MjdjNmU4ZjNkMWE5MTIyYzEyZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pAybMSRbYVBO1p9Dh8P7_BDMZP1vSIT0VqF4lwbSjQI">

@rgaudin can you tell me which icon is wrong ?

**Comment by rgaudin** [comment]
The one you see top left. that's not a zim icon but the other category icon in the app.

Only zim added via catalog shows their icons

**Comment by BPerlakiH** [comment]
I think I have the same file, on the current main branch it looks good after adding it:
<img width="535" alt="Screenshot 2024-06-29 at 00 40 53" src="https://github.com/kiwix/kiwix-apple/assets/6784320/7bfb94cc-ff6e-4642-b9a2-d3afe6b1b897">

**Comment by BPerlakiH** [comment]
I think the same happened for @kelson42 as well, after the iOS update, the files must have been re-added to the local DB, and from then on they were fixed.

**Comment by kelson42** [comment]
Moving to 3.5.0

**Comment by rgaudin** [comment]
> The code change itself won't change the image data already written into the local DB, before the fix.

OK that explains it. Are we OK with this? If yes then this ticket should be closed
