### ISSUE TITLE
Implement „Find in page“

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-apple#79]
"Search in Android not only finds pages, but matching terms within a page as well. Very helpful in longer articles."
(copied from beta tester feedback)

**Comment by kelson42** [comment]
@automactic Please keep one ticket per issue. If you want to gather tickets together you have many systems, like tags, milestones, projects.

**Comment by automactic** [comment]
I disagree. If you want to keep issue count down or wish to keep issues from becoming stale, the content of the tickets needs to be small and actionable items. IMO, we need to decide what can and should appear in the issue section of the project. 

If you want to keep feature request in the issue section, this is fine by me. But please also don't expect me to be able to quickly resolve issues that needs significant engineering efforts and planning. (i.e. expect issues to go stale)

**Comment by kelson42** [comment]
@automactic I for sure don't want to keep **artificially** ticket count down and avoid stalled. Tickets should reflect the reality. This is mandatory to understand the status of the project and I do my best to secure a high quality ticket portfolio. Here are the guidelines to report bugs https://github.com/kiwix/overview/blob/master/REPORT_BUG.md, please let me know if something is unclear.

**Comment by nk9** [comment]
It looks like this is the single issue being used for both iOS and Mac. Will the UI for this really be the same between the two? For example, one of the duped issues asked for Cmd+F to open this. That affordance makes sense on Mac but not iOS. I appreciate that the code base is the same for both but I'm wondering if it wouldn't be clearer to separate the issues by platform to account for differences like this. I suppose there could be a third bug for common code, but that feels like overkill.

Either way, we need to define how this UI will work on both platforms so that it can be implemented.

I am happy to lend a hand on this issue. I am new to the project, however. Is this a straightforward first issue for someone with a bit of Swift experience?

**Comment by kelson42** [comment]
@nk9 Both versions, macOS and iOS use now the dame code base. Obviously, the keyboard shortcuts are not available on iOS. Regarding the implementation, such a feature has to use the HTML render builtin for the core of the feature. Regarding the UI, it's true that the situation is quite open but I woukd try to do like in Web browsers. How this has been solved in Safari/Chrome/Firefox?

**Comment by nk9** [comment]
We're using a `WKWebView`, so it should be as easy as invoking the [web view's `find` method](https://developer.apple.com/documentation/webkit/wkwebview/3650493-find).

I've downloaded the source, will give it a shot and see if I can make a PR. If someone else wants to do it first, be my guest!

**Comment by kelson42** [comment]
@nk9 Have you been able to make progresses? Meanwhile we have published the xcf and updated the README. It should be very easy to step-in now. This is a very important feature. Getting it done would be a nice milestone!

**Comment by VitoVan** [comment]
This feature is the one I'm currently craving.

🙏 🙏 🙏

I wish I knew some Swift and macOS programming.

**Comment by kelson42** [comment]
@VitoVan This is scheduled for next release :)

**Comment by kelson42** [comment]
@BPerlakiH How complex would it be to implement this feature?

**Comment by BPerlakiH** [comment]
@kelson42 @Popolechien Please see my PR on this here: https://github.com/kiwix/kiwix-apple/pull/849

**Comment by kelson42** [comment]
Feature seems unavailable if I open a content from "open new tab", see
<img width="1080" alt="image" src="https://github.com/user-attachments/assets/f81e7795-a38e-4e18-8fab-838ac187193c">
