### ISSUE TITLE
Change url scheme from "kiwix://" to "zim://"

### ISSUE THREAD

**Issue by BPerlakiH** [kiwix/kiwix-apple#798]
We want to update all in app urls to have a scheme "zim://" instead of "kiwix://".
Note: we might need to migrate the user bookmarks, to make things back-ward compatible as well.

**Comment by kelson42** [comment]
@BPerlakiH Here is the small [documentation about the URLs](https://github.com/kiwix/libkiwix/wiki/ZIM-URLs), obviously use relative URL when needed.

**Comment by kelson42** [comment]
@BPerlakiH Please first make a PR to handle in a generic fashion this kind of data migration challenge.
