### ISSUE TITLE
Stop displaying a dialog box, if content of a framset or oframe is missing

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-apple#799]
See https://github.com/kiwix/kiwix-apple/issues/779#issuecomment-2153311537

instead it should display a blanck page or an error.

**Comment by BPerlakiH** [comment]
@kelson42 it has been fixed as part of the: https://github.com/kiwix/kiwix-apple/pull/797
It was just very poorly communicated (even I had trouble finding it :)
It was in the PR description:
"Fixed the issue with the error pop-up, now only a failing "main" document should trigger the pop-up."
