### ISSUE TITLE
Video does not stop in tab is close

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-apple#803]
On my iPad iOS 18 Beta, if I Play a Video and then close the tab, then the Video (Sound) continues in the backgroud.

But it should Not, the video Soundtrack should stop.

**Comment by benoit74** [comment]
Which tab are you referring too? There are tabs in kiwix-apple (I have none on MacOS, so I'm a bit suprised there would be tabs in iOS)?

Are you referring to the fact that you put the application in the background? Or are you really closing the application?

**Comment by kelson42** [comment]
Yes, we have tabs on iOS, and we have Money on macOS (I can Not Test anymore), then we should Open a Feature request.
