### ISSUE TITLE
Can't read Zim files

### ISSUE THREAD

**Issue by sonlin54** [kiwix/kiwix-apple#807]
I have a Mac OS Chromebook
When I download files from Kwix library it states it cant find Zim files.
Perhaps tell me how to do these downloads properly
Not computer savy
Please help

**Comment by kelson42** [comment]
@sonlin54 Thank you for your issue. Which version of macOS and which version of Kiwix do you have?

**Comment by kelson42** [comment]
Actually chromebook is not an apple device so not sure what you have installedmactually. The Kiwix versions number would be very helpful.

**Comment by benoit74** [comment]
> Actually chromebook is not an apple device so not sure what you have installed actually

Technically speaking, you can install MacOS on a Chromebook ... but this is kinda very geeky, so pretty sure something is wrong in original comment. Agreed that Kiwix version number would help, you can find it in "About Kiwix" in the top left corner of your screen if you are really on MacOS:

![image](https://github.com/kiwix/kiwix-apple/assets/7102089/905d0396-9dfd-48c4-91cb-81cbe14ecef9)

**Comment by sonlin54** [comment]
Thank you for your quick response

HP Chromebook 14A G5
OP system Chrome OS
125.0.6422.140.64

As for Kwix  I downloaded for Mac OS

**Comment by kelson42** [comment]
Kiwix for macOS and iOS can not run on Chromebooks.

We don't have a dedicated version of Kiwix for Chromebook, but the PWA version should work, see https://pwa.kiwix.org/. If you have access to the Android PlayStore, the Android version of Kiwix might work as well. None of these two solutions have been tested on Chromebook, but your feedback would be welcome anyway.
