### ISSUE TITLE
Integrate Codecov to the CI

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-apple#808]
... and create a badge in the Readme.

**Comment by kelson42** [comment]
Alos time to implement that one

**Comment by BPerlakiH** [comment]
Initially it seems we are on 34,7%:

<img width="1042" alt="Screenshot 2024-08-04 at 16 04 40" src="https://github.com/user-attachments/assets/33545a68-b739-4cc9-ab3d-a6faae39db66">
