### ISSUE TITLE
Under certain condition opening ZIM (homepage) gives a black screen

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-apple#818]
See for example:
<img width="1080" alt="image" src="https://github.com/kiwix/kiwix-apple/assets/1029718/4b62ab74-2ff2-403c-8202-89dfbec068d9">

No reproduction steps so far

**Comment by kelson42** [comment]
Actually I have a reproduction case, it happens if I try to reopen (after closing its tab) a ZIM file if Kiwix went on hibernation.

**Comment by kelson42** [comment]
@BPerlakiH @mgautierfr @rgaudin To me here we face a similar root cause like #772. I believe the core of the problem might be that if the app is hibernated and then resumed, the filedescriptors are lost. Could we try to confirmnthis theory?

**Comment by BPerlakiH** [comment]
So far I have found that if the Kiwix app is in background, and there's a genuine low memory error on device, after which foregrounding the Kiwix app, it will have this error, when we try to re-open a tab.

**Comment by kelson42** [comment]
> So far I have found that if the Kiwix app is in background, and there's a genuine low memory error on device, after which foregrounding the Kiwix app, it will have this error, when we try to re-open a tab. 

Which error? What would be your proposal?
