### ISSUE TITLE
Improve bookmark data for PDF files

### ISSUE THREAD

**Issue by BPerlakiH** [kiwix/kiwix-apple#827]
Following up the issue of #826 
We might consider using more data from the PDF files for the purpose of creating bookmarks.
The following fields are displayed from Bookmarks:
- title 
- (optional) short snippet
- (optional) image url

**Comment by kelson42** [comment]
At this stage my question is: Is that a good idea at all to have an image and a snippet extracted from the article? Do we really need that? Are we aware that such a requirement might a serious impact in term of code complexity to be done properly (next question would be the support of a Video file for example)?

**Comment by BPerlakiH** [comment]
@kelson42 I have created a proposition and a draft PR, to help you with this question: https://github.com/kiwix/kiwix-apple/pull/830

**Comment by BPerlakiH** [comment]
I think it can be now closed, as the bookmark PR is merged.
