### ISSUE TITLE
iOS: Unable to open file (which works in Kiwix elsewhere)

### ISSUE THREAD

**Issue by stuartlangridge** [kiwix/kiwix-apple#842]
I have created a .zim file for myself, and it happily opens in kiwix-desktop on Ubuntu. However, when I download that file (with Safari) on my iPhone, and then try to open it in Kiwix for iOS from the Downloads folder, Kiwix responds "Unable to open file: blah.zim cannot be opened". Is there any way I can find out _why_ it can't be opened, so I can work to resolve it? There does not seem to be a way; the syslog on the device does not seem to mention the file by name, so I don't think that Kiwix is NSLog()ing a failure reason, although I might be wrong about that. I did not (and cannot) compile my own Kiwix; I'm just using the one from the Apple app store for iOS.

**Comment by kelson42** [comment]
Thank you @stuartlangridge, you should definitly be able to open your ZIM files and have a similar user experience on all versions of Kiwix.

Let me as you two questions:
* How have you created your ZIM file? With which tool?
* Do you ise Kiwix 3.4.0 for iOS released today?

**Comment by stuartlangridge** [comment]
> * How have you created your ZIM file? With which tool?

I used the Python bindings for libzim to create my zim file, as packaged in Ubuntu 22.04. These seem to be 1.0.0+ds-2build1, based on libzim in Ubuntu which is version 7.2.0-2build1.

 I was not using v3.4.0 of Kiwix for iOS, but I have just updated to that and tried again and I have the same issue.

(I should note that I have opened a different zim file from inside the Kiwix interface and that worked, so my Kiwix installation for iOS isn't completely broken or anything!)

**Comment by kelson42** [comment]
@stuartlangridge OK, then its looks like a bug. Would you be able to share the ZIM file, or any ZIM file suffering of the bug?

**Comment by kelson42** [comment]
@stuartlangridge It seems as well that you use a very old version of python-libzim, any chance you could use the latest version published on pypi?

**Comment by stuartlangridge** [comment]
I have just tried using `libzim` from pypi, and I still get the problem, it seems. You can grab a small example file which shows the problem (it loads fine in kiwix-desktop, but does not in kiwix-ios) from https://kryogenix.org/random/fr-small-pip.zim.

**Comment by kelson42** [comment]
@stuartlangridge I rna `zimcheck` against your file, and I see:
```
[ERROR] Metadata errors:
  Missing mandatory metadata: Language
  Missing mandatory metadata: Date
  Missing mandatory metadata: Illustration_48x48@1
```
At this stage, I guess there is 50% chance that the rootcause of the problem is there because [these Metadata are mandatory in the ZIM spec](https://wiki.openzim.org/wiki/Metadata). Would you be able to set them and try again?

**Comment by stuartlangridge** [comment]
Aha, I didn't know there was a zimcheck tool! Now that I know that I'll try again and verify with zimcheck, thank you.

**Comment by stuartlangridge** [comment]
...and that has indeed fixed it! My created zim file now opens fine in Kiwix for iOS, now that I've added language, date, and illustration.

I shall file a bug against the python libzim bindings because their example code in their README does not include these mandatory elements, but this bug can be closed, and thank you!

**Comment by kelson42** [comment]
@rgaudin @benoit74 Actually I believe this is not really normal that a ZIM file can be written without error by python-libzim if the ZIM file can not be open afterward.

**Comment by rgaudin** [comment]
python-libzim is a wrapper. If libzim allows it, pylibzim should as well

**Comment by kelson42** [comment]
@mgautierfr  ?

**Comment by kelson42** [comment]
I will transfer to `openzim/libzim`.

**Comment by kelson42** [comment]
Kamino closed and cloned this issue to [openzim/libzim](https://github.com/openzim/libzim/issues/901)
