### ISSUE TITLE
No search result when the key word more than 1 byte with Chinese zim files

### ISSUE THREAD

**Issue by macligithub** [kiwix/kiwix-apple#847]
When I updated to 3.4.0 version and search 1 Chinese byte, it seems work well, but when I try to search more than 1 byte, No search result.

For example: if you search “西班牙”, it will show “no result".
it's normal in old version.

English zim is no problem.

**Comment by kelson42** [comment]
@macligithub What is the content you use?

**Comment by macligithub** [comment]
The content is: wikipedia_zh_all_maxi_2024-04.zim, but I think it infect all of Chinese zim files.

**Comment by macligithub** [comment]
Also I have noticed that the new software menu has changed to Chinese also, any connection between the menu language and this problem?

**Comment by kelson42** [comment]
@macligithub Pretty sure I know the problem, but may I ask you to download/test with ifixit in chinese https://library.kiwix.org/#lang=&q=chinese&category=iFixit ? I believe that content should be searchable in Chinese.

**Comment by macligithub** [comment]
Tested iFixit in Chinese file, search function is fine as you said. :)
