### ISSUE TITLE
Double-clicking on a ZIM in finder opens a new Kiwix window

### ISSUE THREAD

**Issue by benoit74** [kiwix/kiwix-apple#850]
While https://github.com/kiwix/kiwix-apple/issues/699 seems to have solved some problems of new windows, I still get too many windows in following scenario:
- Kiwix app is already opened (minimized or not)
- I double-click a ZIM in Finder
- A new Kiwix app window opens

And this continues every times I click a ZIM.

https://github.com/kiwix/kiwix-apple/assets/7102089/543c948d-7ed5-40f9-9c69-bfc10e85aa1e

**Comment by kelson42** [comment]
@BPerlakiH Can you please do all the necessary that we never have more than one Kiwix window open once and that even are all run in the unique single window?

**Comment by benoit74** [comment]
After some thought, I'm not sure this is what we want. It might be useful to have two reader windows side-by-side in some occasions. But maybe this is a feature request.

What is really anoying here is that it opens a new window + it doesn't open the ZIM main page but the reading catalog. If it did open the ZIM main page, it would be far more understandable by the user. But again, this is maybe a feature request.

**Comment by kelson42** [comment]
> After some thought, I'm not sure this is what we want. It might be useful to have two reader windows side-by-side in some occasions. But maybe this is a feature request.

For the moment this is the requirement at least and by experience, nobody has ever really complained about this choice (at least not on Windows/Linux). Please open an other issue if this is an important topic to you
 
> What is really annoying here is that it opens a new window + it doesn't open the ZIM main page but the reading catalog. If it did open the ZIM main page, it would be far more understandable by the user. But again, this is maybe a feature request.

100% agree with that, this is something I already complained in the past. @BPerlakiH Can you fix this as well please?

**Comment by BPerlakiH** [comment]
Thank you @benoit74 for clarifying, I think it makes more sense now. I will try to fix it in a way to open the tapped ZIM in the new window.
