### ISSUE TITLE
Crash 3.4.0 - libxml2.2.dylib: xmlMallocZero +48

### ISSUE THREAD

**Issue by BPerlakiH** [kiwix/kiwix-apple#853]
<img width="547" alt="Screenshot 2024-07-10 at 11 30 28" src="https://github.com/kiwix/kiwix-apple/assets/6784320/932480b8-f71e-4d35-bc02-0c221ed64d5c">

**Comment by BPerlakiH** [comment]
@kelson42 I had a deeper look at this.
We have a dependency called `Fuzi`, which is a swift wrapper around `libxml2`.
It is linking the system provided version of `libxml2` [at build time](https://github.com/cezheng/Fuzi/blob/master/Package.swift#L14).

There's a couple of issues, it won't fail properly if initialised with invalid xml/html content data, there's already [a long standing issue on that on Fuzi's side](https://github.com/cezheng/Fuzi/pull/128).

I [implemented the proposed changes for that](https://github.com/cezheng/Fuzi/pull/128), and linked my version of Fuzi to the project, but it's still not 100%, as it is not failing properly under all conditions. Additional to that some issues have been already fixed in the underlying libxml2 as well. comparing my local version (2.09) and [the latest libxml2 version](https://gitlab.gnome.org/GNOME/libxml2/-/releases).

We have a couple of options here, bearing in mind that **only 2 devices crashed**:
- **A)** try to enforce the latest version of libxml2 by manually adding it and linking it, and use a fork of Fuzi for that
- **B)** switch Fuzi and libxml2 to something else (quality of 3rd party packages might vary, so there's no guarantee it will be an actual improvement)
- **C)** we use the html parsing in 2 places, the search and the bookmark. For the bookmarks there's already [a proposition to remove the html parsing](https://github.com/kiwix/kiwix-apple/pull/830). We can do the same for search. The difference is:

## Search results with default html parsing option (first sentence):
<img width="823" alt="Screenshot 2024-07-13 at 13 01 35" src="https://github.com/user-attachments/assets/1f713906-d1ef-4cb8-ace1-2dd8cb9a9174">

## Search results with html parsing disabled:
<img width="862" alt="Screenshot 2024-07-13 at 13 01 20" src="https://github.com/user-attachments/assets/137f9484-604f-4c42-a06a-b75b085a71ad">

We can be more subtle here, either: 
- **C1)** disable this functionality in the next release, so the html parsing won't be used, if we find a better replacement for it we can re-enable it. 
- **C2)** Remove html parsing completely, including the feature flag and settings of this.
- **D)** Postpone this fix

**Comment by kelson42** [comment]
@BPerlakiH Thank you for the analysis. Please make a PR to remove for bookmarks. For search results, the libkiwix has a function to provide the HTML snippet, so I don't understand why this is not used!

**Comment by BPerlakiH** [comment]
Thank you @kelson42.
Here's the updated PR to remove bookmarks: https://github.com/kiwix/kiwix-apple/pull/830.
As part of the issue then, I will look into how we could use the html snippet from libkiwix, instead of this parsing.

**Comment by BPerlakiH** [comment]
Ok, I figured this out. We have 4 options to display some extra field as part of the  search results.
It can be:
- Disabled
- First paragraph
- First sentence
- Matches

First paragraph and First sentence is using the html parser to get some more info from the content.
Matches, is actually using what you were referring to @kelson42 , which is the matching snippet from libzim.
If we turn on "matches", the results may vary, as we have 2 types of search results, one where the title is matching, one is matching the indexed content:
<img width="834" alt="Screenshot 2024-07-13 at 21 35 49" src="https://github.com/user-attachments/assets/fe8d0af2-c235-4c50-bc66-fc85825d1c29">

As you can see, where the title matches there's no additional info, whereas where the content is matching there's an extra field.

This is is to be compared with the default behaviour (First Paragraph):
<img width="523" alt="Screenshot 2024-07-13 at 21 37 45" src="https://github.com/user-attachments/assets/da2b290e-f699-4500-bd35-f16f20571e29">
