### ISSUE TITLE
Running kiwix on older ios versions

### ISSUE THREAD

**Issue by Afdusrt** [kiwix/kiwix-apple#880]
I use an iPhone that I wish to use kiwi x on, that is running iOS 15.8.2. however, i cannot find how to build an IPA. Do you have old IPA files archived somewhere?

**Comment by kelson42** [comment]
@Afdusrt We don't release IPA files, but AFAIK ITunes still provide older versions of Kiwix for older iOS versions which are not supported anymore by most recent version of Kiwix.
