### ISSUE TITLE
Increased text size setting in iOS cuts off items in the bottom menu

### ISSUE THREAD

**Issue by ronaldl29** [kiwix/kiwix-apple#883]
Here is a screenshot of the issue. The back button is cut off. 
![IMG_1508](https://github.com/user-attachments/assets/96a88728-5454-4ff4-8194-b4ea566f0375)

This happens when the text size setting is increased in iOS. 
![IMG_1509](https://github.com/user-attachments/assets/8071dd57-3971-4afd-8866-b39140b8489a)

**Comment by kelson42** [comment]
@ronaldl29 Thank you for yor bug report. Can you please share with us both versions of iOS and Kiwix running on your device?

**Comment by ronaldl29** [comment]
Thank you for the quick response!

Kiwix v3.4.0
iOS 17.5.1

@kelson42

**Comment by kelson42** [comment]
@ronaldl29 Perfect, I have put this bug in the next milestone 3.5.0 and hopefuly this will be fixed within a few weeks.

**Comment by ronaldl29** [comment]
You guys are awesome. Thank you!

**Comment by BPerlakiH** [comment]
Please see the fix here with screenshots: https://github.com/kiwix/kiwix-apple/pull/886
