### ISSUE TITLE
WKURLSchemeHandler crash

### ISSUE THREAD

**Issue by BPerlakiH** [kiwix/kiwix-apple#895]
## Background:

We are handling the incoming requests via: [WKURLSchemeHandler](https://developer.apple.com/documentation/webkit/wkurlschemehandler), which has 2 functions:
- start [WKURLSchemeTask](https://developer.apple.com/documentation/webkit/wkurlschemetask)
- stop [WKURLSchemeTask](https://developer.apple.com/documentation/webkit/wkurlschemetask)

Based on the request attached to the [task](https://developer.apple.com/documentation/webkit/wkurlschemetask), we load the content and we can:
- send the header, later send the content, we can send more content if needed, finish the task
- finish the task with an error

According to Apple's rules we are not allowed to:
- send the header multiple times
- send headers or data to a task, if it was finished or errored out earlier (and wasn't restarted)

The source code for all the possible exceptions can be found here:
https://opensource.apple.com/source/WebKit2/WebKit2-7604.3.5/UIProcess/API/Cocoa/WKURLSchemeTask.mm.auto.html

## Current solution
Our current approach is to store the hash of these tasks, and based on the [handling functions](https://developer.apple.com/documentation/webkit/wkurlschemetask) we register which tasks were already started, and which were stopped, trying to make sure that we won't violate any of the above rules.

## The crash
It is occurring both on the main branch and the [range-request](https://github.com/kiwix/kiwix-apple/pull/894) branch as well, if we start an mp4 video file, and seeking heavily within that back and forth.

It is occurring both on the iPhone and on macOS.

## Initial conclusions:
Since it is occurring on both branches: it is not due to the way we handle the range-requests. It does seems though, that having the range-requests in place, this problem is more prominent (possibly due to a higher throughput of the requests).

[Other posts suggests](https://www.stevesouders.com/blog/2013/04/21/html5-video-bytes-on-ios/), that the video player might drop the connection on various points by itself. It might be (not confirmed) that we are not informed about this fact (via Apple's [callback functions](https://developer.apple.com/documentation/webkit/wkurlschemetask)) which can lead to a crash.

## Findings
It seems that the tasks themselves are "re-cycled", meaning that their hash and underlying objectIDs are re-occurring in debug logs, as being started, headers + data sent, finished, stopped, and started again. Unfortunately there's no direct sequence that leads to the crash, eg: an objectID might be re-used (as described above) several times, and later crashing. 

## Former attempts, that failed so far:
- Artificially slowing down the response time has no effect on this crash, it can even make it worse (meaning it might occur more often).
- A couple of ways to store the hash of these tasks, making sure it can be read / write in a concurrent way.
- Using hand made hashes based on the content of the request content (and not the task)

## Possible things to try:
- Minimise any concurrency (possible race conditions, and "re-entrance")
- See if it's possible via objective-c to store the "state" of the task within the task (currently our storage is an external to the tasks dictionary, which has the hashes of the tasks that has been started, and the ones stopped are removed from there).
- See if it's possible to get around the exceptions thrown

**Comment by wallace757** [comment]
https://nasirregimen.github.io/custom-model-binder/
