### ISSUE TITLE
Continue playing video even when Kiwix app has not the focus anymore

### ISSUE THREAD

**Issue by benoit74** [kiwix/kiwix-apple#898]
I would like that the videos continue playing even when Kiwix app has not the focus anymore.

At least on MacOS, since Kiwix 3.4.1 (171), when Kiwix app looses the focus the video stops automatically.

This is probably a side effect of https://github.com/kiwix/kiwix-apple/pull/891

I don't know if this is a bug or a feature request.

**Comment by benoit74** [comment]
I just noted that the video also stops when exiting fullscreen, it would be cool if the video could continue to play (if I'm not mistaken, I think it is the usual behavior in most app).

**Comment by benoit74** [comment]
(might be a side-effect of https://github.com/kiwix/kiwix-apple/pull/893 as well)

**Comment by BPerlakiH** [comment]
Thank you @benoit74, nice catch.
Actually we were receiving notification from the full screen video window, which is not "ours".
On the same callback we are also deleting the tab... which also kicked in by exiting the full screen video... auch...

Now it is fixed here:
https://github.com/kiwix/kiwix-apple/pull/899

**Comment by benoit74** [comment]
Nice, will test it with next testflight build

**Comment by benoit74** [comment]
I confirm it works well, nice !
