### ISSUE TITLE
Not all files to download are visible

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-apple#902]
If I search for "bug" online, I get:
<img width="1080" alt="image" src="https://github.com/user-attachments/assets/bb1372ea-303a-4b5a-a00c-b7974dc0b50a">

If I search for "bug" in library, I get:
<img width="1080" alt="image" src="https://github.com/user-attachments/assets/e3984af9-2922-4280-be49-4a54d851ea21">

I should not get different resulta IMHO, at least not for this search!

**Comment by BPerlakiH** [comment]
@kelson42 as of my initial findings it seems that we use the libzim search function for these results, which currently only searching amongst the titles of the zim files, and not the descriptions. As of: https://wiki.openzim.org/wiki/Libzim#using_the_Search-class

It would be great to know how exactly the website search works, and what should be the possible fix for this:
A) update the libzim search to match what's on the website
B) update the website to match what's in libzim
C) do the search as on the website (using the local (reader side) DB with a similar query

**Comment by BPerlakiH** [comment]
I can confirm, that by modifying the search query to use both "name CONTAINS" or fileDescription CONTAINS" does return both results. So that it working for this specific case. 
The only question remains: is that good enough (as it's now a guess how the website search might work), or do we want an exact match ?

**Comment by BPerlakiH** [comment]
My other, slightly related concern about how the search works is that it's really hard to find a ZIM that is not "new". Currently the user can search only within the selected category (eg. "Other"), but that is a very strict rule, I think. We assume that the user knows which category that ZIM belongs to... 
Putting it another way: we have no "global search" (eg: search in all categories).

**Comment by kelson42** [comment]
Reopening as I believe we should do more than this.

**Comment by kelson42** [comment]
> My other, slightly related concern about how the search works is that it's really hard to find a ZIM that is not "new". Currently the user can search only within the selected category (eg. "Other"), but that is a very strict rule, I think. We assume that the user knows which category that ZIM belongs to...
> Putting it another way: we have no "global search" (eg: search in all categories).

@BPerlakiH I agree. Please open an issue just for that and put it in next milestone.

**Comment by kelson42** [comment]
@BPerlakiH To complete this PR, can you change 1 month in 3 months because 1 month is really too short.

**Comment by BPerlakiH** [comment]
Increased the lifespan of "NEW" to be 3 months here: https://github.com/kiwix/kiwix-apple/pull/910

**Comment by BPerlakiH** [comment]
new issue created here: https://github.com/kiwix/kiwix-apple/issues/911

**Comment by kelson42** [comment]
Seems even more broken thab before now!
<img width="1080" alt="image" src="https://github.com/user-attachments/assets/929b31d9-8b6d-430e-815c-5128ed76c9b0">

**Comment by BPerlakiH** [comment]
Hmm, interesting. It looks as if the catalog was empty...
I can see both files on my end.
Can you try to do a "refresh" with the button:
<img width="99" alt="Screenshot 2024-08-11 at 10 50 12" src="https://github.com/user-attachments/assets/c4051a9d-4f26-4b66-ad4b-4be50eef2409">

**Comment by kelson42** [comment]
> Hmm, interesting. It looks as if the catalog was empty...
> 
> I can see both ZIM files as a search result on my end.
> 
> Can you try to do a "refresh" with the button:
> 
> <img width="99" alt="Screenshot 2024-08-11 at 10 50 12" src="https://github.com/user-attachments/assets/c4051a9d-4f26-4b66-ad4b-4be50eef2409">

Library is refreshed.

**Comment by BPerlakiH** [comment]
Did the refresh solve the issue?

**Comment by kelson42** [comment]
No

**Comment by BPerlakiH** [comment]
Can you do a screenshot of the "New" section when the search query is empty, and also one screenshot of "Settings > Languages" ?

**Comment by BPerlakiH** [comment]
Both of those results are in "English" only, so if you only have other language(s) selected, there won't be any result for that query.

**Comment by kelson42** [comment]
<img width="1080" alt="image" src="https://github.com/user-attachments/assets/9bb21793-7626-4279-8c07-8f80a7c0e41f">

<img width="1080" alt="image" src="https://github.com/user-attachments/assets/0921f836-f416-4d4e-8c93-3b791a9c3482">

**Comment by kelson42** [comment]
Works now with latest testflight of this morning... somI guess the fix was still not included. Closing.
