### ISSUE TITLE
Library language count is wrong

### ISSUE THREAD

**Issue by BPerlakiH** [kiwix/kiwix-apple#905]
As pointed out here: 
https://github.com/kiwix/kiwix-apple/pull/903#issuecomment-2266711639

The language count, and listing is incorrect, as now we support multiple languages (comma separated in the DB) per each ZIM file.

Although the proposed solution in the above PR works, we want a more testable, and more separated solution, we can reason about.

We should also cover more edge cases, to make sure this listing is always correct.

**Comment by kelson42** [comment]
It should work but please keep in mind tha milestone 3.6.0 is about using libkiwix to do all of that properly (what is does), so does not make sense to invest to much of energy to fix "everything".
