### ISSUE TITLE
Missing UI

### ISSUE THREAD

**Issue by minidog0** [kiwix/kiwix-apple#909]
The bottom menu bar is cut off on my iPhone SE2. I can't click the gear.
![IMG_2827](https://github.com/user-attachments/assets/5e42e3c7-86ab-4e3d-aeb5-13f1cec98662)

**Comment by minidog0** [comment]
[bug] [question](https://github.com/kiwix/kiwix-apple/issues?q=is%3Aissue+is%3Aopen+label%3Aquestion)

**Comment by BPerlakiH** [comment]
@minidog0 Thank you for reporting this issue.
We have fixed this problem as part of the PR: https://github.com/kiwix/kiwix-apple/pull/886
It will be included in our next 3.5.0 release.

In the meantime, in "Settings" > "Accessibility" > "Display & Text Size" if you reduce the text size, the tab bar icons will be smaller, and will fit horizontally on your device screen, and you can access them.
