### ISSUE TITLE
iPad Video.js play pause button state 

### ISSUE THREAD

**Issue by BPerlakiH** [kiwix/kiwix-apple#914]
After closing full screen, the video.js play / pause button is stuck on pause state, it does work, but not updating it’s state.

**Comment by kelson42** [comment]
I can not reproduce this bug on iOS18. Can we have please a details bug report with a screencast?

**Comment by BPerlakiH** [comment]
@kelson42 this is the screen recording from iPad iOS 17:

https://github.com/user-attachments/assets/5bf20764-8dad-46dc-ab0a-6ac17be99410

TLDR: the play/pause button works at the beginning, after returning from full-screen, it does work (pauses and plays the video), but the state of the button is not changing.

**Comment by BPerlakiH** [comment]
These are the 2 states of the button:
<img width="58" alt="Screenshot 2024-08-12 at 23 30 36" src="https://github.com/user-attachments/assets/5d7b24d8-4575-4efd-8187-2edf4ead96f6">
<img width="55" alt="Screenshot 2024-08-12 at 23 30 44" src="https://github.com/user-attachments/assets/b89e7ac1-f2b0-4781-b019-5e28c8434d3f">

**Comment by kelson42** [comment]
@BPerlakiH Old content, not even distributed anymore: please redo a screencast with the most recent ZIM content.

**Comment by BPerlakiH** [comment]
@kelson42 The same issue with newer content, on iPad OS 17:
https://github.com/user-attachments/assets/393eb204-9a9d-4e48-aeb1-411c5e99b7c7

Reproduction steps:
- start playing a video
- enter full screen
- exit full screen, this pauses the video => expect to see the button: 
![image](https://github.com/user-attachments/assets/9ce05d06-c261-4196-be9f-f549c3417200)
- play video => expect to see the button:
![image](https://github.com/user-attachments/assets/e3ed7e0b-019a-4703-8f93-6553994c4a3c)
- pause video => expect to see the button:
![image](https://github.com/user-attachments/assets/9ce05d06-c261-4196-be9f-f549c3417200)

**Comment by benoit74** [comment]
To me this looks a lot like Video.JS bug, to be reported to Video.JS repository.

Do you have the same behavior on Safari or with Kiwix app (if you can force it to load a web URL) on https://videojs.com/city?

**Comment by BPerlakiH** [comment]
@benoit
I have tested in Safari and force loaded the url into the Kiwix app, both works fine.
"Our" content is using: Video.js 7.8.1
Whereas the [latest release](https://github.com/videojs/video.js/releases) is: 8.17.2

**Comment by benoit74** [comment]
Thank you! Sorry for this new test (hopefully the last one), but can you please test https://mirror.download.kiwix.org/zim/videos/deus-ex-silicium_fr_all_2024-08.zim ; it is a (very) fresh ZIM with video.js 8.17.3 (which is not even marked latest, but we needed this in youtube scraper to support Chrome 58 and 59, and video.js maintainer told us it was fine and going to be latest soon).

**Comment by BPerlakiH** [comment]
@benoit74 No worries.
I've downloaded and tested the ZIM, and **it works great**.
So, it seems that the video.js update alone can solve this issue for us.

**Comment by kelson42** [comment]
@benoit74 Can we link here to the issues requesting this version of video.js? For each of the scraper relying ont video.js?

**Comment by BPerlakiH** [comment]
@kelson42 @benoit74 I have also tested the same ZIM file on the iPhone, there's one behaviour that is different there (compared to other ZIM files), is that the video starts playing immediately as the page loads, and switches to full screen, which makes our [other issue with the black start screen](https://github.com/kiwix/kiwix-apple/issues/916) more prominent:


https://github.com/user-attachments/assets/21fa9392-f916-416f-8d09-e49d688568b4

**Comment by BPerlakiH** [comment]
I am happy to close this issue, as with the latest ZIM file and video js it is resolved.

**Comment by benoit74** [comment]
> @benoit74 Can we link here to the issues requesting this version of video.js? For each of the scraper relying ont video.js?

Sure:
- [ ] [kolibri](https://github.com/openzim/kolibri):  https://github.com/openzim/kolibri/issues/127
- [ ] [nautilus](https://github.com/openzim/nautilus): https://github.com/openzim/nautilus/issues/91
- [ ] [ted](https://github.com/openzim/ted): https://github.com/openzim/ted/issues/225
- [x] [youtube](https://github.com/openzim/youtube): https://github.com/openzim/youtube/issues/275, fixed with https://github.com/openzim/youtube/pull/290
