### ISSUE TITLE
iPhone backgrounding makes the inline video black

### ISSUE THREAD

**Issue by BPerlakiH** [kiwix/kiwix-apple#917]
Backgrounding and switching to another app, and then foregrounding the Kiwix app, makes the video screen black, similar to the iPad issue: https://github.com/kiwix/kiwix-apple/issues/772
If we apply the same workaround we did for iPad, that causes the video to go into full screen, although the user left it not full screen / “inline”.

**Comment by kelson42** [comment]
Proposal is to use a similar approach like https://github.com/kiwix/kiwix-apple/pull/846/files but for iPhones.

**Comment by BPerlakiH** [comment]
Initially it seems that fixing the other issue first: https://github.com/kiwix/kiwix-apple/issues/933
would make this fix easier.
