### ISSUE TITLE
Translation issue with message Kiwix:Apple-bookmark button.show.help/ja

### ISSUE THREAD

**Issue by HiroyasuNishiyama** [kiwix/kiwix-apple#927]
Message URL: https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=apple-bookmark_button.show.help&group=kiwix-apple&language=ja

I translated this string, but I have a question.

I might be misunderstanding since I'm not very familiar with accessibility features, but it seems that this string is used for voiceover of the menu. 

In my environment (iPhone and iPad), I found that opening the menu is done with a double-tap, not a long press in voiceover mode.

**Comment by kelson42** [comment]
@BPerlakiH Can you please clarify/fix?

**Comment by BPerlakiH** [comment]
@HiroyasuNishiyama Thank you, you are right. This is the accessibility label for the show bookmarks sheet on iOS.
I have updated the description and the English version of it here:
https://github.com/kiwix/kiwix-apple/pull/930
