### ISSUE TITLE
Translation issue with message Kiwix:Apple-flavor tag.help.no pic/ja

### ISSUE THREAD

**Issue by HiroyasuNishiyama** [kiwix/kiwix-apple#928]
Message URL: https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=apple-flavor_tag.help.no_pic&group=kiwix-apple&language=ja

The localization key (`flavor_tag.help.no_pic`) does not seem to be used. 

Perhaps, `flavor-no-pic-description` in the following line is incorrect.

https://github.com/kiwix/kiwix-apple/blob/27fa440a5bf8de6ee075e092678d10812dce5a32/Views/BuildingBlocks/FlavorTag.swift#L53

**Comment by kelson42** [comment]
@BPerlakiH Can younplease clarify/fix?

**Comment by BPerlakiH** [comment]
Thank you @HiroyasuNishiyama, indeed that key was wrong, please see it fixed here: https://github.com/kiwix/kiwix-apple/pull/929
