### ISSUE TITLE
Logo of Kiwix should not be inverted in dark mode

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-apple#934]
See, this is the only one inverted!
<img width="1080" alt="image" src="https://github.com/user-attachments/assets/d55e4ca0-edda-44ed-b664-bdb9f5b73c47">

I would like to have the same logo, so black kiwix on white background, so stay like the "Proton VPN" logo.

**Comment by BPerlakiH** [comment]
@kelson42 It is not reproducible on iOS 17 (neither on the iPhone nor on the iPad), and works as expected on macOS as well.
It seems to me that this is not a bug, but a new iOS 18 feature:
https://www.apple.com/newsroom/2024/06/ios-18-makes-iphone-more-personal-capable-and-intelligent-than-ever/

**Comment by kelson42** [comment]
Postponing then

**Comment by kelson42** [comment]
@BPerlakiH Can you please handle that one next?

**Comment by rgaudin** [comment]
@kelson42 from your screenshot, it looks like we are doing things properly: our logo being a black shape, it is inverted to white on dark background – the background being provided by the system.

On your screenshot, you see that there are two kinds of icons:
- background providing ones: Github, Uptime robot, Calc, etc (I count 12)
- Background-less ones: All the rest including Kiwix, Stripe, etc (I count 18).

All those background-less ones have probably not updated their app to support this new iOS18 feature (at the time of the screenshot it was a month before the release) and I suppose most will do in the near future (if not already).

Deciding to go with a background-providing icon is an important design decision that should de discussed first IMO.

With iOS18, we have this new feature but we (can) have control over it

<img width="910" alt="Screenshot 2024-09-20 at 09 58 52" src="https://github.com/user-attachments/assets/9a6c618f-ae54-44fe-ac1f-fc281e1646f9">

I suggest we (@siemsie) read the documentation about what is recommended and what is possible and then we discuss how this gets implemented

- [Providing images for different appearances](https://developer.apple.com/documentation/uikit/uiimage/providing_images_for_different_appearances)
- [Configuring your app icon](https://developer.apple.com/documentation/xcode/configuring-your-app-icon/)

**Comment by BPerlakiH** [comment]
Also please note that we are implementing the reversed logo look for the splash/launch/loading screens here: https://github.com/kiwix/kiwix-apple/pull/976

So I suppose for consistency reasons, we should either allow to reverse the logo colours everywhere (app icon, launch screen etc.), or nowhere.

**Comment by kelson42** [comment]
At this stage, I can not reproduce the problem with cutting edge iOS 18.1 version
![Image](https://github.com/user-attachments/assets/fe556f7b-3a18-44ae-9e96-75211d4104d6)

... and new tinted feature seems to work well as well
![Image](https://github.com/user-attachments/assets/5bd86d73-1a26-463d-88a2-7e03537114a8)

Therefore I believe I have to close this issue

**Comment by siemsie** [comment]
Hi. I agree that we should stay on a light background and not invert the Kiwix logo. Something like this... I used a transparency gradient – that can be done right to respect the background colours?

I've also added a size suggestion as above I feel the logo isn't balanced in the space... Being irregular in shape it's best to keep it a little more "central" and less close to the edges. What do you think? Could it work?

![Image](https://github.com/user-attachments/assets/363a16a8-87c8-4a74-9383-9c972aa8bf19)

**Comment by kelson42** [comment]
@siemsie Thank you!
@BPerlakiH Do you need anything else to move forward?
