### ISSUE TITLE
No Results for Chinese Search Queries

### ISSUE THREAD

**Issue by nani-kun** [kiwix/kiwix-apple#935]
When I search for Chinese entries with more than two characters, I get no results, even though the entries exist. This issue wasn't present in previous versions. Please fix it. Thank you.

![IMG_7045](https://github.com/user-attachments/assets/8e035fee-6d51-4d09-9784-fa145ef29c6d)

**Comment by BPerlakiH** [comment]
@nani-kun Thank you for reporting it. 
Please add the following information so we can investigate it:
- exact former version number where it is working
- the current version number you are using where it is not working
- the search query itself, in text format (currently we only have your screenshot)

**Comment by kelson42** [comment]
This is a know bug which is actually in the ZIM file. I will close a duplicate.
