### ISSUE TITLE
Release tag seems wrong

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-apple#971]
For some reason it is `testflight-3.5.2` and it should be `3.5.2`

Unclear - at least right now - to me why we don't have a proper tag.

**Comment by BPerlakiH** [comment]
It seems to me that we are re-using the tags that were used to created the TestFlight releases (and which was approved by Apple), and we do not create a new tag.

**Comment by kelson42** [comment]
To me the workflow should be as such:
* Tag `testflight` when you want to do Testflight release. If this tag already exists, then remove/superseeds older version.
* If we make a release tag `x.y.z` and release in GitHub.
* Released version trigger the publishing in testflight but only such a version can make it through production.
* If there is a problem with Apple validation - post release - then a patch release has to be made.

**Comment by BPerlakiH** [comment]
I've updated the readme and the CD workflow to reflect the above requirements.
