### ISSUE TITLE
Improve launch sequence

### ISSUE THREAD

**Issue by BPerlakiH** [kiwix/kiwix-apple#975]
## The problem:
Currently there's no splash screen on iOS, and the initial loading state is not shown to the user. This results in a completely white screen on app start, for relatively long time:

https://github.com/user-attachments/assets/f00712a6-b31a-411f-a718-a9ad0b2c022e

**Comment by BPerlakiH** [comment]
@kelson42 I double checked it, there's no way to add an animated gif to the splash screen. That would animate properly.

**Comment by kelson42** [comment]
@BPerlakiH Then I guess we will have to keep current approach. Le see how looks next screen cast you will upload.
