### ISSUE TITLE
Add support of libkiwix14

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-apple#984]
Libkiwix 14 [is almost over](https://github.com/kiwix/libkiwix/milestone/12), we should use it when released.

Blocked by https://github.com/kiwix/libkiwix/issues/1081

**Comment by kelson42** [comment]
@BPerlakiH Can you please make a draft PR and check that everything is OK before the libkiwix 14 release (using nightly)?

**Comment by BPerlakiH** [comment]
@kelson42  from the errors on the PR it seems to me that the iOS simulator is not included in the target framework build of libkiwix.

Also it is substantially smaller than the former package here:
https://download.kiwix.org/release/libkiwix/

> [   ] [libkiwix_xcframework-13.1.0.tar.gz](https://download.kiwix.org/release/libkiwix/libkiwix_xcframework-13.1.0.tar.gz)      2024-02-25 15:17  195M   
[   ] [libkiwix_xcframework-14.0.0.tar.gz](https://download.kiwix.org/release/libkiwix/libkiwix_xcframework-14.0.0.tar.gz)      2024-10-11 14:37   59M

**Comment by kelson42** [comment]
@rgaudin The explanation of @BPerlakiH seems the most logical... but not clear where is the regression. We should not have touch that part, but I suspect that somehow a something has been broken. Could you please have a look please?

**Comment by rgaudin** [comment]
![Image](https://github.com/user-attachments/assets/3f748a8b-0f0e-4f9a-8c68-48be51268d26)

No, it seems all archs are present but all are significantly smaller. Looks like an embedded-dependency issue

**Comment by kelson42** [comment]
@rgaudin Can we easily have a look to latest working and see where is the difference?

**Comment by rgaudin** [comment]
Not sure exactly but building raises this ; which is exactly what the CI logs shows

![Image](https://github.com/user-attachments/assets/6812e952-e3f1-41b9-ab06-3100a24365f6)

Are we depending on libgss?

**Comment by kelson42** [comment]
Kind of suspect the regression is around libcurl... and this commit might be interesting https://github.com/kiwix/kiwix-build/commit/23a6b93fcc200004b222811fbb5adc23814e9eda

**Comment by rgaudin** [comment]
This is fixed at https://github.com/kiwix/kiwix-build/pull/765.

Once @kelson42 merges it and we have a nightly, we'll be able to test. It will require adding `      - sdk: SystemConfiguration.framework` to the `project.yml`

**Comment by BPerlakiH** [comment]
``SystemConfiguration.framework`` is added now, waiting for the new build.

**Comment by rgaudin** [comment]
@BPerlakiH yes that was expected but since the nightly workflow ran so I tested with https://download.kiwix.org/nightly/2024-10-18/libkiwix_xcframework-2024-10-18.tar.gz but that didn't work.

On a second thought, that's normal as the fix was not in libkiwix (which `main` branch is compiled in the nightly) but in the `libcurl` dependency. We thus need to request a new revision of the dependencies (as those are cached). @kelson42 can you do it?
