### ISSUE TITLE
Users complain not finding zim file after download

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-apple#985]
I had two successive users trying to download [S2 Underground](https://library.kiwix.org/#lang=eng&q=s2) zim file (3.6Gb) and reporting that the file was nowhere to be found. 

They both used iOS 14 and would not / could not help more than that, so can someone please check whether there is an actual issue?

**Comment by kelson42** [comment]
We don't support iOS 14 since ios17 release which pretty exactly obe year ago. Therefore I suspect they use an old version of Kiwix and it will be hard to provide support.

@BPerlakiH Anything to add?

**Comment by Popolechien** [comment]
Ok thanks for the clarification and my bad, the last report said iPhone 14, not iOS 14.

**Comment by BPerlakiH** [comment]
I did download the latest S2 Underground content (10 Sep 2024), and it does work for me on my iPhone, so it's not likely to be a content issue.

Depending on network conditions, the download might take some time. The current progress should be visible under the "Downloads" tab of the application. 
If the download fails, the user is informed about it.

We need more information to investigate this, maybe a screen shot / recording of the issue, the current Kiwix app version they are using (on iPhone it's under the Settings icon (bottom right corner) / About).
