### ISSUE TITLE
Large download (wikipedia_en_all_maxi) does not complete after 99%

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-apple#992]
From a user:

> Hi—
> Am unable download Wikipedia max (109.89 GB) after 5 separate _nearly_ successful attempts.
> After watching the % download creep up to 99% and the downloaded amount reach 109+ GB over 1-3 hrs, the screen suddenly switches to “Download” (again!) with no error messages.
> Where did it go?
> The Wikipedia no pic & Wikipedia mini download normally but are significantly less useful.
> iPhone 15 Pro iOS 18 ~870 GB free memory. Same result w/ or w/o VPN.
> Please advise.
> Thank you,

Should I request more information?

**Comment by kelson42** [comment]
@BPerlakiH Can you please confirm quickly it works for you?

**Comment by NightFuryStrike** [comment]
I can confirm that I am experiencing the same issue.
(iPhone 16 Pro Max 512GB)
Version 3.5.2 - Build 173

**Comment by BPerlakiH** [comment]
I did some quick investigation on this. It seems that once the download finishes, it "jumps back" to the state before the download for a short while, even on small downloads. For larger ones, it might take longer. Will investigate it further.

**Comment by kelson42** [comment]
> I did some quick investigation on this. It seems that once the download finishes, it "jumps back" to the state before the download for a short while, even on small downloads. For larger ones, it might take longer. Will investigate it further.

Thank you very much, this is a TOP prio to fix what looks like to be a real bug.

**Comment by BPerlakiH** [comment]
There's a PR for this, in the meantime, it seems that only the UI part of the download is affected, so from a user perspective, with the current version of the app, once the download completes it will go back to the "downloadable" state. At this point if the user waits enough time for the file to be moved and opened, the UI should update, and they can use the ZIM file correctly. 
Fix is coming for this in release 3.60.
