### ISSUE TITLE
Deleting a book should delete related tabs

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-apple#993]
But it does not!
![IMG_2716](https://github.com/user-attachments/assets/cd5315fd-e326-4b3a-8eac-9f9d034d0997)

**Comment by BPerlakiH** [comment]
I couldn't recreate this on iPad 17. The tabs related to the ZIM file that was deleted are closing properly. 
Can you provide more specific steps please?

**Comment by kelson42** [comment]
I don't remember, but might that be that this is related to "unlink" vs "delete" book?

**Comment by BPerlakiH** [comment]
Ok, with "unlink" it's also working on iPad 17, will switch to iPad 18, and see how that works.
